theme: "hugo-lithium"
baseURL: "/"
languageCode: en-us
title: Government of Canada Contract Analysis

params:
  feedbackFormLink: "https://docs.google.com/forms/d/e/1FAIpQLSfHGzAQMaOkj4OD2Kc8Gw4ROChOfx6MKm5t2CSr6R4U2qupBQ/viewform?usp=pp_url&entry.739845506={url}"
# https://docs.google.com/forms/d/e/1FAIpQLSfHGzAQMaOkj4OD2Kc8Gw4ROChOfx6MKm5t2CSr6R4U2qupBQ/viewform?usp=pp_url&entry.739845506=/departments/ppsc-sppc/

ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$

permalinks:
  vendor: /vendors/:slugorfilename/
  department: /departments/:slugorfilename/
  category: /categories/:slugorfilename/
  overall: /:slugorfilename/
  meta: /:slugorfilename/

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true

menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Methodology
      url: /methodology/
      weight: 2
    - name: Guide to reforming IT procurement
      url: /it-procurement-guide/
      weight: 3
    - name: Data visualizations
      url: /data-visualizations/
      weight: 4
    - name: About the project
      url: /about/
      weight: 5
