theme: "hugo-lithium"
baseURL: "/"
languageCode: en-us
title: Government of Canada Contract Analysis

ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$

permalinks:
  vendor: /vendors/:slugorfilename/
  department: /departments/:slugorfilename/
  category: /categories/:slugorfilename/
  overall: /:slugorfilename/

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
